import { toPng } from 'html-to-image';
import {
  Document,
  Packer,
  Paragraph,
  ImageRun,
  HeadingLevel,
  AlignmentType,
} from 'docx';
import PptxGenJS from 'pptxgenjs';

/**
 * Get the ReactFlow viewport element and capture it as a PNG data URL.
 * Uses the entire .react-flow container and filters out overlays.
 */
async function captureCanvas() {
  const wrapper = document.querySelector('.react-flow');
  if (!wrapper) throw new Error('Canvas not found');

  const { width, height } = wrapper.getBoundingClientRect();

  const dataUrl = await toPng(wrapper, {
    backgroundColor: '#0a0e1a',
    width: Math.ceil(width),
    height: Math.ceil(height),
    pixelRatio: 2,
    filter: (node) => {
      /* Skip overlays that shouldn't be in the export */
      if (!node || !node.classList) return true;
      if (node.classList.contains('react-flow__minimap')) return false;
      if (node.classList.contains('react-flow__controls')) return false;
      if (node.classList.contains('react-flow__attribution')) return false;
      if (node.classList.contains('react-flow__panel')) return false;
      return true;
    },
  });
  return dataUrl;
}

/**
 * Convert a data URL to a Uint8Array of bytes.
 */
function dataUrlToUint8Array(dataUrl) {
  const base64 = dataUrl.split(',')[1];
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/* ─────────────────────────────────────────────
   PNG Export
   ───────────────────────────────────────────── */
export async function exportPNG() {
  try {
    const dataUrl = await captureCanvas();
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = 'flowchart.png';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  } catch (err) {
    console.error('PNG export failed:', err);
    alert('Failed to export PNG. Error: ' + err.message);
  }
}

/* ─────────────────────────────────────────────
   DOCX Export
   ───────────────────────────────────────────── */
export async function exportDOCX() {
  try {
    const dataUrl = await captureCanvas();
    const imageBytes = dataUrlToUint8Array(dataUrl);

    const doc = new Document({
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 720,
                right: 720,
                bottom: 720,
                left: 720,
              },
            },
          },
          children: [
            new Paragraph({
              children: [
                new ImageRun({
                  data: imageBytes,
                  transformation: {
                    width: 600,
                    height: 400,
                  },
                  type: 'png',
                }),
              ],
              alignment: AlignmentType.CENTER,
            }),
            new Paragraph({
              text: 'Generated by FlowCraft',
              heading: HeadingLevel.HEADING_3,
              alignment: AlignmentType.CENTER,
              spacing: { before: 400 },
            }),
          ],
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'flowchart.docx';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (err) {
    console.error('DOCX export failed:', err);
    alert('Failed to export DOCX. Error: ' + err.message);
  }
}

/* ─────────────────────────────────────────────
   PPTX Export
   ───────────────────────────────────────────── */
export async function exportPPTX() {
  try {
    const dataUrl = await captureCanvas();

    const pptx = new PptxGenJS();
    pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
    pptx.layout = 'WIDE';

    const slide = pptx.addSlide();
    slide.background = { color: '0a0e1a' };

    slide.addImage({
      data: dataUrl,
      x: 0.5,
      y: 0.5,
      w: 12.33,
      h: 6.0,
    });

    slide.addText('Generated by FlowCraft', {
      x: 0,
      y: 6.8,
      w: 13.33,
      h: 0.5,
      fontSize: 10,
      color: '94a3b8',
      align: 'center',
      fontFace: 'Inter',
    });

    await pptx.writeFile({ fileName: 'flowchart.pptx' });
  } catch (err) {
    console.error('PPTX export failed:', err);
    alert('Failed to export PPTX. Error: ' + err.message);
  }
}
